% Generated by MATLAB(R) 9.13 (R2022b) and Bluetooth Toolbox 1.1 (R2022b).
% Generated on: 04-Feb-2023 20:59:52

%% Bluetooth Low Energy 波形を生成しています
% Bluetooth Low Energy 構成
sps = 8; % 
symbolRate = 1000000;
numPackets=20;

for packetIdx = 1:numPackets
    % input bit source:
    in = randi([0, 1], 200, 1);
    
    % 生成
    waveform = bleWaveformGenerator(in, 'Mode', 'LE1M', ...
        'SamplesPerSymbol', 8, ...
        'ChannelIndex', 39, ...
        'AccessAddress', [1 0 0 0 1 1 1 0 1 0 0 0 1 0 0 1 1 0 1 1 1 1 1 0 1 1 0 1 0 1 1 0]');
    
    Fs = sps * symbolRate; 								 % 波形のサンプル レートを Hz 単位で指定
    % 周波数オフセットの追加修正版.関数を使わず計算式のみで行った.
    % 周波数オフセットの値の作成
    
    %Q_offset=0.0129453893600390;
    I_offset=-0.1
    Q_offset=0.2;
    % I/Q不均衡パラメータの定義
    amp_imbalance = 0;
    phase_imbalance = 0;
    % I/Q不均衡を加える
    re_waveform_IQoff=real(waveform)+I_offset;
    im_waveform_IQoff=imag(waveform)+Q_offset;
    %waveform_FIQ=waveform_FIQ.*cfo.';
    % パスを指定しそこに信号配列ファイルを追加
    numfile=num2str(packetIdx, '%06d');
    filename=append("BLEsignal", numfile);
    pass = 'BLE_Data_IQoff'; % パスの指定
    filenamepass=fullfile(pass,filename);
    save(filenamepass); 
end
%{
%% 可視化
% Spectrum Analyzer
spectrum = spectrumAnalyzer('SampleRate', Fs);
spectrum(waveform);
release(spectrum);

% Constellation Diagram
%{
constel = comm.ConstellationDiagram('ColorFading', true, ...
    'ShowTrajectory', 0, ...
    'ShowReferenceConstellation', false);

step(constel, waveform_FIQ);
release(constel);
%}


% Eye Diagram
%eyediagram(waveform, 2* 8);

% Signal
timeScope = timescope('SampleRate', symbolRate*sps,'TimeSpanSource','Auto',...
    'ShowLegend',true);
% Plot the generated waveform
timeScope.Title = ['Bluetooth LE ',' Waveform for Channel Index = ', '39'];
timeScope(waveform,waveform_F);

% Constellation Diagram
I = real(waveform); % I成分
Q = imag(waveform); % Q成分

hold on; % 複数のグラフを同じFigureにプロットするためにhold onを使用する
scatter(I, Q, '+', 'b'); % scatter plotを作成 blue
hold off;  % hold onの状態を解除する
axis equal;
xlim([-2 2]);
ylim([-2 2]);
xlabel('I'); ylabel('Q'); % x軸とy軸にラベルを付ける
%}