% Generated by MATLAB(R) 9.13 (R2022b) and Bluetooth Toolbox 1.1 (R2022b).
% Generated on: 04-Feb-2023 20:59:52

%% Bluetooth Low Energy 波形を生成しています
% Bluetooth Low Energy 構成
sps = 8; % 
symbolRate = 1000000;
numPackets=20;

for packetIdx = 1:numPackets
    % input bit source:
    in = randi([0, 1], 200, 1);
    
    % 生成
    waveform = bleWaveformGenerator(in, 'Mode', 'LE1M', ...
        'SamplesPerSymbol', 8, ...
        'ChannelIndex', 39, ...
        'AccessAddress', [1 0 0 0 1 1 1 0 1 0 0 0 1 0 0 1 1 0 1 1 1 1 1 0 1 1 0 1 0 1 1 0]');
    
    Fs = sps * symbolRate; 								 % 波形のサンプル レートを Hz 単位で指定
    % 周波数オフセットの追加修正版.関数を使わず計算式のみで行った.
    % 周波数オフセットの値の作成
    fcfomin=-10000; % 周波数オフセット最小値
    fcfomax=-1000; % 周波数オフセット最大値% BLE規格の周波数オフセットの限界値150e3（これを超すとBluetoothの規格外）
    fcfo=fcfomin + (fcfomax-fcfomin)*rand; % 周波数オフセット配列の生成.1k~100kHzでだけ作る.
    %fcfo=0; % cfoの値を0にする。I・Q けいそくのため
    t=(0:length(waveform)-1)/Fs;
    cfo=exp(1j*2*pi*fcfo*t);
    waveform_F=waveform.*(cfo.');
    re_waveform_F=real(waveform_F);
    im_waveform_F=imag(waveform_F);
    % I/Qオフセットの定義
    I_offset=0.00972502161073269;
    Q_offset=0.0129453893600390;
    % I/Q不均衡パラメータの定義
    amp_imbalance = 0;
    phase_imbalance = 0;
    % I/Q不均衡を加える
    I_imbalanced = real(waveform) * cos(amp_imbalance/2)+imag(waveform)*sin(amp_imbalance/2);
    Q_imbalanced = imag(waveform)*cos(amp_imbalance/2) + real(waveform)*sin((amp_imbalance/2));
    waveform_FIQ=I_imbalanced+I_offset+1j * (Q_imbalanced+Q_offset);
    %waveform_FIQ=waveform_FIQ.*cfo.';
    % パスを指定しそこに信号配列ファイルを追加
    re_waveform_FIQ=real(waveform_FIQ);
    im_waveform_FIQ=imag(waveform_FIQ);
    numfile=num2str(packetIdx, '%06d');
    filename=append("BLEsignal", numfile);
    pass = 'BLE_Signal_Data'; % パスの指定
    filenamepass=fullfile(pass,filename);
    save(filenamepass); 
end
%% 可視化
% Spectrum Analyzer
spectrum = spectrumAnalyzer('SampleRate', Fs);
spectrum(waveform,waveform_FIQ);
release(spectrum);

% Constellation Diagram
%{
constel = comm.ConstellationDiagram('ColorFading', true, ...
    'ShowTrajectory', 0, ...
    'ShowReferenceConstellation', false);

step(constel, waveform_FIQ);
release(constel);
%}


% Eye Diagram
%eyediagram(waveform, 2* 8);

% Signal
timeScope = timescope('SampleRate', symbolRate*sps,'TimeSpanSource','Auto',...
    'ShowLegend',true);
% Plot the generated waveform
timeScope.Title = ['Bluetooth LE ',' Waveform for Channel Index = ', '39'];
timeScope(waveform,waveform_F);

% Constellation Diagram
I = real(waveform); % I成分
Q = imag(waveform); % Q成分
I2 = real(waveform_FIQ);
Q2 = imag(waveform_FIQ);
I3 = real(waveform_F);
Q3 = imag(waveform_F);
hold on; % 複数のグラフを同じFigureにプロットするためにhold onを使用する
scatter(I, Q, '+', 'b'); % scatter plotを作成 blue
scatter(I2, Q2, '.','r'); % scatter plotを作成 red
scatter(I3, Q3, '.','g'); % scatter plotを作成 green
hold off;  % hold onの状態を解除する
axis equal;
xlim([-2 2]);
ylim([-2 2]);
xlabel('I'); ylabel('Q'); % x軸とy軸にラベルを付ける